### ISSUE TITLE
Support dgraph 1.1+

### ISSUE THREAD

**Issue by jnylen** [ondrowan/dgraph-cli#1]
Hi @ondrowan,

I'm just creating this issue for a feature request of support dgraph 1.1+.

Hopefully I can help you with this, but as I haven't really done anything big in rust I might probably not be of any help at all.

**Comment by ondrowan** [comment]
Hey there and thanks for interest! I can implement it sometime during next week, but I need to figure out how to do it. Since there are still users using 1.0, I don't think I should drop support for it. I have recently finally added 1.1 support to `dgraph-rs`, but it is using feature flags to enable it. I'm not sure if it's possible to include the same dependency with different feature flags and use it as different libraries in code.

**Comment by ondrowan** [comment]
@jnylen Sorry for the delay, I was swamped with work stuff and forgot about this. Since you are most likely the only user of this crate, I will upgrade `dgraph` crate to one that supports just Dgraph 1.1+ and add 1.0 support only if someone asks for it. I have already started to work on this, but unfortunately some API in Dgraph changed and I'll have to rewrite certain parts of the application. I should finish it during next days.

**Comment by ondrowan** [comment]
@jnylen I have pushed the changes into master. Could you confirm it works as expected?
